name: Trading Bot

on:
  schedule:
    - cron: "0 * * * *"   # every 1 hour
  workflow_dispatch:       # allows manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check secrets (debug)
        run: |
          echo "API_KEY is set: ${{ secrets.API_KEY != '' }}"
          echo "ACCESS_TOKEN is set: ${{ secrets.ACCESS_TOKEN != '' }}"
          echo "ACCESS_TOKEN_SECRET is set: ${{ secrets.ACCESS_TOKEN_SECRET != '' }}"
          echo "API_SECRET is set: ${{ secrets.API_SECRET != '' }}"
          echo "BEARER_TOKEN is set: ${{ secrets.BEARER_TOKEN != '' }}"

      - name: Run bot
        run: python bot.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
